"""
Author: Ali (Troxter222)
Project: MUG (Molecular Universe Generator)
Date: 2025
License: MIT
"""

import os
import datetime
from fpdf import FPDF

class ResearchReport(FPDF):
    def header(self):
        # Логотип или заголовок
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0, 51, 102) # Dark Blue
        self.cell(0, 10, 'MUG: Computational Drug Discovery Report', 0, 1, 'C')
        self.ln(5)
        # Линия
        self.set_draw_color(0, 51, 102)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by MUG AI (v7.4)', 0, 0, 'C')

class ReportingService:
    @staticmethod
    def generate_pdf(mol_name, smiles, props, affinity, image_path, recipe, filename="report.pdf"):
        pdf = ResearchReport()
        pdf.add_page()
        
        # 1. Заголовок молекулы
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Candidate: {mol_name[:40]}...", 0, 1, 'L')
        
        # Дата
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'L')
        pdf.ln(5)
        
        # 2. Абстракт (Научное описание)
        pdf.set_font("Arial", "B", 12)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 8, "  1. Abstract Analysis", 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font("Arial", "", 11)
        aff_text = f"{affinity} kcal/mol" if affinity else "N/A (QSAR only)"
        abstract = (
            f"The proposed chemical entity represents a de novo generated scaffold targeting specific "
            f"protein binding pockets. In silico evaluation predicts a binding affinity of {aff_text}. "
            f"The calculated drug-likeness (QED) score is {props['qed']}, suggesting favorable oral bioavailability characteristics. "
            f"The compound has a molecular weight of {props['mw']} Da."
        )
        pdf.multi_cell(0, 6, abstract)
        pdf.ln(5)
        
        # 3. Визуализация
        # Центрируем картинку
        if os.path.exists(image_path):
            x_pos = (210 - 100) / 2
            pdf.image(image_path, x=x_pos, w=100)
            pdf.ln(5)
        
        # 4. Свойства (Таблица)
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "  2. Physicochemical Profile", 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font("Courier", "", 10)
        # Простое форматирование колонок
        col_w = 45
        pdf.cell(col_w, 8, f"MW: {props['mw']} Da", 1)
        pdf.cell(col_w, 8, f"LogP: {props['logp']}", 1)
        pdf.cell(col_w, 8, f"TPSA: {props['tpsa']} A^2", 1)
        pdf.cell(col_w, 8, f"QED: {props['qed']}", 1)
        pdf.ln(8)
        pdf.cell(0, 8, f"SMILES: {smiles[:75]}...", 1)
        pdf.ln(12)
        
        # 5. Токсикология и Риски
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "  3. Safety & Synthesis", 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font("Arial", "", 11)
        
        # Риски красным цветом, если они есть
        if "No obvious alerts" in props['risk_profile']:
            pdf.set_text_color(0, 128, 0)
            pdf.cell(0, 8, "Toxicology: Clean (No structural alerts detected)", 0, 1)
        else:
            pdf.set_text_color(192, 0, 0)
            pdf.multi_cell(0, 6, f"Toxicology Flags: {props['risk_profile']}")
            
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)
        pdf.multi_cell(0, 6, f"Synthesis Route:\n{recipe}")

        # Сохранение
        pdf.output(filename)
        return filename